### ISSUE TITLE
Design an error handling system for volga

### ISSUE THREAD

**Issue by yefrig** [yefrig/coms4995-oss#17]

**Comment by eozmen410** [comment]
We should probably define our own `Exception`s, 

Precedents we can draw from:
- [pickle](https://github.com/python/cpython/blob/3.9/Lib/pickle.py) has `UnpicklingError` and `PicklingError`s defined 
- [marshmallow](https://github.com/marshmallow-code/marshmallow/blob/43db1072f94ae6af40cbedc058f1c02f3cedb379/src/marshmallow/fields.py#L23) has custom exceptions as well
